name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar Flet
        run: pip install flet

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build APK
        run: flet build apk --module-name teste

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/apk/*.apk
