name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar Flet
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.24.0"

      - name: Modo não interativo
        run: echo "FLET_FORCE_NON_INTERACTIVE=1" >> $GITHUB_ENV

      - name: Gerar APK
        run: |
          flet build apk \
            --module-name teste \
            --yes \
            --verbose

      - name: Verificar arquivos gerados
        run: |
          echo "Conteúdo da pasta build:"
          find build -type f

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MeuAppFlet-APK
          path: build/apk/*.apk
          if-no-files-found: error
